export const ENV_KEYS = {
  MONGO_URI: 'MONGO_URI',
  JWT_SECRET: 'JWT_SECRET',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  BASE_URL: 'BASE_URL',
  CLIENT_URL: 'CLIENT_URL',
  SUPPORT_EMAIL: 'SUPPORT_EMAIL',
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
};
